services:
  app:
    build: .
    environment:
      POSTGRES_USER: postgres
      DB_HOST_NAME: db
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: coding-test
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
