version: '3'

services:
  db:
    platform: linux/x86_64
    image: postgres:15
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
    - "${DB_PORT:-5432}:5432"

  app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./test_app:/app
    ports:
      - ${APP_PORT:-8000}:8000
    command: /bin/sh -c "python manage.py runserver 0.0.0.0:8000"
    tty: true
    stdin_open: true
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_volume:
