# Generated by Django 4.2.5 on 2023-09-05 01:30

from django.db import migrations, models
import uuid

def add_initial_companies(apps, schema_editor):
    Company = apps.get_model('Company', 'Company')

    # 初期企業データの追加
    company_names = ['ソニー', 'LG', 'Nvidia']

    for name in company_names:
        Company.objects.create(
            id=uuid.uuid4(),
            name=name
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(db_comment='企業ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='企業名', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新日時')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
                'db_table_comment': '企業テーブル',
            },
        ),
        migrations.RunPython(add_initial_companies),
    ]
