# Generated by Django 4.2.6 on 2023-10-14 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, db_comment='親カテゴリID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.category'),
        ),
    ]
